# This is a development tool to run the DREAM.3D GUI in the Docker container
# Usage:
#   docker compose -f docker-compose-dream3d-gui.yaml up --build

services:
  dream3d:
    build:
      context: .
      dockerfile: Dockerfile
      target: gui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/opt/microtexture/src
      - ./Sample_ANG_Files:/data:rw
    environment:
      - DISPLAY=${DISPLAY:-:0}
    user: 1000:1000
    working_dir: /data
    network_mode: host
    entrypoint: ""
    command: "DREAM3D"
