# Used to manually build a Docker image for DREAM3D 6.5.171
# Usage:
#   docker buildx build . -f ./Dockerfile.dream3d-6.5.171 -t ghcr.io/uomresearchit/dream3d:6.5.171

FROM ubuntu:24.04 AS dream3d

# Install DREAM3D ----
RUN apt-get update && apt-get install -y \
    wget \
    tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/dream3d

# The DREAM3D tar ball used to be available using:
# RUN wget https://dream3d.bluequartz.net/binaries/DREAM3D-6.5.171-Linux-x86_64.tar.gz
# It currently has to be downloaded manually, e.g. from the Wayback Machine:
# https://web.archive.org/web/20240924110350/https://dream3d.bluequartz.net/binaries/DREAM3D-6.5.171-Linux-x86_64.tar.gz
COPY DREAM3D-6.5.171-Linux-x86_64.tar.gz ./
RUN tar -xvzf DREAM3D-6.5.171-Linux-x86_64.tar.gz --strip-components=1

# DREAM3D runtime dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender1 \
    libx11-xcb-dev \
    libxcb-util-dev \
    libxkbcommon-x11-dev \
    && rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/opt/dream3d/lib
ENV QT_PLUGIN_PATH=/opt/dream3d/Plugins
ENV QT_QPA_PLATFORM_PLUGIN_PATH=/opt/dream3d/Plugins/platforms

RUN mkdir -p /tmp/runtime-root && chmod 0700 /tmp/runtime-root
ENV XDG_RUNTIME_DIR=/tmp/runtime-root

ENV PATH="/opt/dream3d/bin:${PATH}"

ENTRYPOINT [""]
CMD ["DREAM3D"]
